<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['certificate_manager_app_description'] = 'Сертификаты безопасности являются отраслевым стандартом для шифрования информации, посланной по сети, обеспечивая аутентификацию и позволяет цифровые подписи. Приложение "Диспетчер сертификатов" обеспечивает возможность создания, управления и развертывания сертификатов безопасности для пользователей и приложений.';
$lang['certificate_manager_app_name'] = 'Диспетчер сертификатов';
$lang['certificate_manager_certificate'] = 'Сертификат';
$lang['certificate_manager_certificate_already_exists'] = 'Сертификат уже существует.';
$lang['certificate_manager_certificate_authority'] = 'Центр сертификации';
$lang['certificate_manager_certificate_authority_help'] = 'В целях повышения общей безопасности вашей системы, сертификаты безопасности требуются для доступа к многим приложениям. Вы вероятно привыкли видеть предупреждение о сертификате в веб-браузере, аналогичной показанной на скриншоте. Начиная с запуска центра сертификации, начинается ваше путешествие с сертификатом безопасности!';
$lang['certificate_manager_certificate_change_warning'] = 'После создания сертификатов по умолчанию может быть временно разъединен Ваш веб-браузер. Пожалуйста, не пугайтесь, если вы видите сообщение с предупреждением безопасности после обновления.';
$lang['certificate_manager_certificate_invalid'] = 'Сертификат недействителен.';
$lang['certificate_manager_certificate_manager'] = 'Диспетчер сертификатов';
$lang['certificate_manager_certificate_not_found'] = 'Сертификат не найден.';
$lang['certificate_manager_certificate_request_invalid'] = 'Запрос сертификата - инвалид.';
$lang['certificate_manager_certificate_type'] = 'Тип сертификата';
$lang['certificate_manager_certificates'] = 'Сертификаты';
$lang['certificate_manager_common_name_invalid'] = 'Общее название - инвалид.';
$lang['certificate_manager_configure_app_help'] = 'Прежде чем Вы сможете начать использовать это приложение, Вы сначала должны сконфигурировать Сертификаты безопасности.';
$lang['certificate_manager_configure_security_certificates'] = 'Сконфигурируйте сертификаты безопасности';
$lang['certificate_manager_create_certificate'] = 'Создать сертификат';
$lang['certificate_manager_default_certificate'] = 'Сертификат по умолчанию';
$lang['certificate_manager_email_invalid'] = 'Электронная почта - инвалид.';
$lang['certificate_manager_expires'] = 'Истекает';
$lang['certificate_manager_filename'] = 'Имя файла';
$lang['certificate_manager_index_file_missing'] = 'Индексный файл отсутствует.';
$lang['certificate_manager_internet_hostname'] = 'Имя хоста в Интернете';
$lang['certificate_manager_issued'] = 'Выпущено';
$lang['certificate_manager_key_size'] = 'Размер ключа';
$lang['certificate_manager_password_must_begin_with_letter_or_number'] = 'Пароль должен начинаться с буквы или числа.';
$lang['certificate_manager_pkcs12'] = 'PKCS12';
$lang['certificate_manager_private_key'] = 'Закрытый ключ';
$lang['certificate_manager_purpose_invalid'] = 'Цель - инвалид.';
$lang['certificate_manager_security_certificates'] = 'Сертификат безопасности';
$lang['certificate_manager_security_is_important'] = 'Безопасность важна';
$lang['certificate_manager_self_signed'] = 'Самоподписанный';
$lang['certificate_manager_server_certificate'] = 'Сервер сертификатов';
$lang['certificate_manager_system_waiting_for_connection_to_master'] = 'Система ожидает соединения с главным узлом.';
$lang['certificate_manager_third_party'] = 'Третья сторона';
$lang['certificate_manager_web_browser_warning'] = 'Предупреждение веб-браузера';
$lang['certificate_manager_web_browser_warning_description'] = 'Веб-интерфейс автоматически перезагрузится после новых созданных сертификатов безопасности. Вы увидите предупреждение в вашем веб-браузере, похожее на скриншоте ниже. Все хорошо вы можете продолжить безопасно.';
$lang['certificate_manager_web_interface_is_restarting'] = 'Веб-интерфейс перезапускается с новыми сертификатами безопасности.';
$lang['certificate_manager_wizard_description'] = 'В целях повышения общей безопасности вашей системы, сертификаты безопасности требуются для доступа ко многим приложениям.';
