#!/bin/sh

# Prepare certificate storage
#-----------------------

mkdir /etc/clearos/certificate_manager.d/

rm -f /etc/clearos/certificate_manager.d/_default_.crt
rm -f /etc/clearos/certificate_manager.d/_default_.key

ln -s /etc/pki/tls/certs/localhost.crt /etc/clearos/certificate_manager.d/_default_.crt
ln -s /etc/pki/tls/private/localhost.key /etc/clearos/certificate_manager.d/_default_.key

chmod 600 -R /etc/clearos/certificate_manager.d/